packages:
  - 'packages/*'
  - 'docs'
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
